#!/bin/bash

uid=$(id -u ircnet)
gid=$(id -g ircnet)

echo "_.--._.--._.--._.--._.--._.--._.--._.--._.--._.--._.--._.--._.--._.--."
echo "_"
echo "_"
echo "_		Welcome to IRCNet"
echo "_"
echo "_"
echo "_.--._.--._.--._.--._.--._.--._.--._.--._.--._.--._.--._.--._.--._.--."
echo "_"
echo "_"
echo "_		Docker Repo: https://hub.docker.com/r/yanik39/ircnet"
echo "_		Github Repo: https://github.com/TemhAAhmeT/IRCNet"
echo "_"
echo "_"
echo "_.--._.--._.--._.--._.--._.--._.--._.--._.--._.--._.--._.--._.--._.--."
echo "_"
echo "_"
echo "_		Going to check default Files/Folders"
echo "_		Defaults Folder is (/usr/local/ircnet)"
echo "_"
echo "_"
echo "_.--._.--._.--._.--._.--._.--._.--._.--._.--._.--._.--._.--._.--._.--."

if [[ ! -d "/home/ircnet/UnrealIRCd" ]]
then
	echo "Copying default UnrealIRCd folder"
    	mkdir -p /home/ircnet/UnrealIRCd
	cp -r /usr/local/ircnet/UnrealIRCd /home/ircnet
fi
if [[ ! -d "/home/ircnet/Atheme-Services" ]]
then
	echo "Copying default Atheme-Services folder"
    	mkdir -p /home/ircnet/Atheme-Services
	cp -r /usr/local/ircnet/Atheme-Services /home/ircnet
fi
if [[ ! -d "/home/ircnet/theLounge" ]]
then
	echo "Creating default theLounge folder"
    	mkdir -p /home/ircnet/theLounge
	cp -r /usr/local/ircnet/theLounge /home/ircnet
fi
if [[ ! -d "/home/ircnet/Logs" ]]
then
	echo "Creating default Logs folder"
    	mkdir -p /home/ircnet/Logs
fi
if [[ ! -f "/home/ircnet/Supervisor/supervisord.conf" ]]
then
	echo "Copying default Supervisor config file"
	mkdir -p /home/ircnet/Supervisor
    	cp -r /usr/local/ircnet/Supervisor/supervisord.conf /home/ircnet/Supervisor/supervisord.conf
else
	echo "Supervisor config is present"
fi
if [[ ! -f "/help/supervisor_secure" ]]
then
	echo "Creating Supervisor secrets"
	/help/supervisor_secrets.sh
else
	echo "Supervisor is already secured"
fi
if [[ ! -f "/home/ircnet/.bashrc" ]]
then
	echo "Copying Default/Custom .bashrc"
	cp -r /usr/local/ircnet/bashrc /home/ircnet/.bashrc
fi
if [[ ! -f "/help/first_run_done" ]]
then
	echo "Checking Debian updates before First Run"
	echo "Checking Python PIP updates before First Run"
	echo "Checking NodeJS, NPM updates before First Run"
	echo "This can take few minutes..."
    	/bin/bash /help/check_updates.sh	
	echo "System is now UpToDate"
	
	echo "Checking UID and GID"
	[ "$uid" -eq "$UID" ] || usermod -u $UID ircnet &> /dev/null
	[ "$gid" -eq "$GID" ] || groupmod -g $GID ircnet &> /dev/null
	
	echo "Creating symbolic links for Python"
	ln -s /usr/local/bin/python3.10 /usr/bin/python
	ln -s /usr/local/bin/python3.10 /usr/bin/python3
	ln -s /usr/local/bin/python3.10 /usr/bin/python3.10
	
	echo "Setting TimeZone to $TZ"
	ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
	
	echo "Creating User account and setting up Oper block"
	/bin/bash /help/ircnetFirstRun.sh
else
	echo "Not First Run, So skipping updates"
	echo "To update system manually; Please run (/help/check_updates.sh)"
fi

echo "Fixing permissions"
/bin/bash /help/fix_permissions.sh &

echo "_.--._.--._.--._.--._.--._.--._.--._.--._.--._.--._.--._.--._.--._.--."
echo "_"
echo "_"
echo "_		Now, Starting Supervisor for all services"
echo "_"
echo "_"
echo "_.--._.--._.--._.--._.--._.--._.--._.--._.--._.--._.--._.--._.--._.--."

exec /usr/local/bin/python3 /usr/local/bin/supervisord -c /etc/supervisor/supervisord.conf
